version: '0.1'

services:
  openldap:
    image: bitnami/openldap:latest
    hostname: openldap
    container_name: openldap_guacamole
    ports:
      - 1389:1389
      - 1636:1636
    env_file:
      - openldap.dev.env
    restart: always
    volumes:
      #- ./.data/certs:/bitnami/certs
  guacd:
    image: guacamole/guacd:latest
    container_name: guacd_guacamole
    ports:
      - 4822:4822
    env_file:
      - guacamole.dev.env
    restart: always
    volumes:
      - ./.data/guacd/drive:/drive:rw
      - ./.data/guacd/record:/record:rw
  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    ports:
      - 80:8080
    env_file:
      - guacamole.dev.env
    restart: always
    links:
      - guacd
      - openldap